name: 予約投稿 自動ビルド

on:
  schedule:
    - cron: '0 3 * * 3'   # 水曜日 12:00 JST
    - cron: '0 12 * * 5'  # 金曜日 21:00 JST
    - cron: '0 10 * * 0'  # 日曜日 19:00 JST
  workflow_dispatch:       # 手動実行も可能

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Pages デプロイ
        run: |
          curl -d "" "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/7efc5142-f6e3-4298-a508-19be6c9d5b58"
